name: package release
run-name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"
jobs:
  package-and-upload-release-asset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: TAG=${{ github.ref_name }} make release.tgz
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: release.tgz
